version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=dynamodb
      - TZ=Asia/Tokyo
      - DEFAULT_REGION=us-east-1
    ports:
      - 4566:4566
  dynamodb-admin: 
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    ports:
      - 8001:8001
    depends_on:
      - localstack
  go-lambda-app:
    container_name: "go-lambda-app"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DYNAMODB_TABLE=go-lamdba-tutorial-dev
      - QUERY_INDEX=record_type-index
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    ports:
      - 9000:8080
    command: ["/main"]
    depends_on:
      - localstack